#pragma once

#define DEFAULT_LOOP_CYCLE_TIME 20

#define DRIVETRAIN_GEAR_RATIO 3/4

#define INTAKE_FORWARD_BUTTON Controller1.ButtonR1
#define INTAKE_REVERSE_BUTTON Controller1.ButtonR2
#define INTAKE_STOP_BUTTON Controller1.ButtonB
#define INTAKE_DEFAULT_SPEED 85

#define ARM_SPIN_BUTTON Controller1.ButtonL2
#define ARM_TOGGLE_STATE_BUTTON_ID Up
#define ARM_MANUAL_SPEED 95
#define ARM_INTAKE_SPEED 10
#define ARM_MACRO_KP 2.5
#define ARM_MACRO_DEADBAND 1
#define ARM_LOADING_POSITION 20
#define ARM_ALLIANCE_STAKE_POSITION 192
#define ARM_WALL_STAKE_POSITION 0 //DON'T FORGET THIS

#define MOGO_BUTTON_ID A

#define DOINKER_BUTTON_ID X