#pragma once

#define DEFAULT_LOOP_CYCLE_TIME 20

#define SORT_RED_HUE_LOWER_BOUND 0
#define SORT_RED_HUE_UPPER_BOUND 0
#define SORT_BLUE_HUE_LOWER_BOUND 0
#define SORT_BLUE_HUE_UPPER_BOUND 0
#define SORT_DETECT_TO_SORT_DELAY 0
#define SORT_SORT_TO_SORT_CONTINUE 0

#define DRIVETRAIN_GEAR_RATIO 0.75
#define DRIVETRAIN_HORIZONTAL_WHEEL_DIAMETER 2
#define DRIVETRAIN_VERTICAL_WHEEL_DIAMETER 3.25
#define DRIVETRAIN_HORIZONTAL_TO_CENTER_DISTANCE 4.5
#define DRIVETRAIN_VERTICAL_TO_CENTER_DISTANCE 5.5
#define DRIVETRAIN_INERTIAL_SCALE 360

#define INTAKE_FORWARD_BUTTON_ID R1
#define INTAKE_REVERSE_BUTTON_ID R2
#define INTAKE_STOP_BUTTON_ID B
#define INTAKE_DEFAULT_SPEED 95

#define ARM_SPIN_BUTTON_ID L2
#define ARM_TOGGLE_STATE_BUTTON_ID Up
#define ARM_DESCORE_BUTTON_ID L1
#define ARM_MANUAL_SPEED 95
#define ARM_INTAKE_SPEED 10
#define ARM_MACRO_KP 1.5
#define ARM_MACRO_DEADBAND 0
#define ARM_MACRO_KCOS 8
#define ARM_LOADING_POSITION 15
#define ARM_UP_POSITION 90
#define ARM_DESCORE_POSITION 142
#define ARM_WALL_STAKE_POSITION 150
#define ARM_ALIGN_ALLY_POSITION 170
#define ARM_ALLIANCE_STAKE_POSITION 185

#define MOGO_BUTTON_ID A

#define DOINKER_BUTTON_ID X